### ISSUE TITLE
🔌 Plugin System MVP — Tracking Issue

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#259]
- __Policy File Handling__
  - [x] #292
  - [x] #335
  - [x] #329
- __Policy Expression Handling__
  - [x] #260
  - [x] #261
- __Plugin Resolution__
  - [x] #268
  - [x] #283
  - [x] #296
  - [x] #284
- __Plugin Integration__
  - [x] Implement code generation based on gRPC service description with Tonic
  - [x] Wire up gRPC calls to existing analysis execution
  - [x] Use policy file to produce AnalysisTree object
  - [x] Process analysis results using policy expressions

**Comment by alilleybrinker** [comment]
Based on the above, I think this is the current list of remaining tasks:

- [ ] Mark `--config` flag as deprecated, still permit it but warn when used
- [ ] Update reporting code to handle reporting results from plugin-based analyses
- [ ] Produce `AnalysisTree` from policy file
- [ ] Update scoring to handle policy expressions when evaluating score tree
- [ ] Update gRPC service definition to include `repeated string concern` in `Query` message
- [ ] Update gRPC service definition to include an RPC call for plugins to explain what their default query does (for use in reporting)
- [ ] Wire up plugin resolution based on initial plugins in policy file
