### ISSUE TITLE
🛤️ RFD System 2.0 - Tracking Issue

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#386]
- [ ] Convert list of RFDs into table
- [ ] Make the table...
  - [ ] Filterable
  - [ ] Sortable
  - [ ] Searchable
- [ ] Add RFD metadata to RFD pages, including:
  - [ ] Superseded by
  - [ ] Authored by
  - [ ] Last updated on
  - [ ] Labels (list of strings)

**Comment by alilleybrinker** [comment]
For now won't invest time on more complex system. The website now has a table with metadata plus site-wide search that includes RFDs. More features may make sense in a future with more RFDs.
