### ISSUE TITLE
Reporting 2.0 - Tracking Issue

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#390]
- [ ] Write RFD for the new output system design
- [ ] Implement minijinja templates for reporting results and printing errors
- [ ] Implement color handling via functions provided to templates
