### ISSUE TITLE
🛤️ Tracking: Fresh Salsa

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#391]
- [x] Implement RFD7, eliminating push to `crates.io`
- [x] Audit use of Salsa today: https://github.com/mitre/hipcheck/discussions/666
- [x] #785
- [x] Add salsa as a git dependency
- [ ] ~Upgrade to Salsa 2022 (intermediate step)~
- [x] Upgrade to Salsa 3.0 (when ready for use)

**Comment by alilleybrinker** [comment]
Completed! Thanks @patrickjcasey
