### ISSUE TITLE
🛤️ Document the Plugin System - Tracking Issue

### ISSUE THREAD

**Issue by alilleybrinker** [mitre/hipcheck#396]
Will need to document:

- For end-users:
  - [ ] Policy files
  - [ ] Policy expressions
- For plugin-authors:
  - [ ] How to create a plugin binary
    - [ ] gRPC interface
    - [ ] Query Protocol
  - [ ] How to distribute a plugin
    - [ ] Plugin manifest
    - [ ] Plugin download manifest
