### ISSUE TITLE
🛤️ Tracking: Hipcheck Developer Docs

### ISSUE THREAD

**Issue by j-lanson** [mitre/hipcheck#513]
- [x] Overview of important locations in the codebase 
(where is the website content, etc.)
- [x] Plugin Startup and Querying (Core-side)
(salsa, engine query --> query object --> emission to plugin)
- [x] Sessions and message dispatch (SDK-side)

**Comment by j-lanson** [comment]
Closed by #728
