### ISSUE TITLE
🛤️ Tracking: Policy Expression Typechecking

### ISSUE THREAD

**Issue by j-lanson** [mitre/hipcheck#677]
- [ ] Replace handling of policy exprs in core as `String` with `Expr`
- [ ] Type-check expressions when parsed from policy file / retrieved from "get_default_policy_expression" gRPC call
- [ ] Ensure Type-checking and JSON-pointer insertion are done before expr evaluation
